# Generated by Django 5.2 on 2025-06-13 14:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_commissioningprofile_level_1_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='algo_enabled',
            field=models.BooleanField(default=False, help_text='Whether algorithmic trading is enabled for this account.'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current equity of the trading account.', max_digits=12),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current margin of the trading account.', max_digits=12),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='margin_free',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Free margin available in the trading account.', max_digits=12),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='margin_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current margin level of the trading account.', max_digits=12),
        ),
    ]
