# Generated by Django 5.2 on 2025-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_tradingaccount_algo_enabled_tradingaccount_equity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='branch',
            new_name='branch_name',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetails',
            name='currency',
            field=models.CharField(default='BTC', max_length=10),
        ),
        migrations.AddField(
            model_name='cryptodetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
