# Generated by Django 5.2 on 2025-06-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_rename_branch_bankdetails_branch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptodetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cryptodetails',
            name='updated_at',
        ),
    ]
