# Generated by Django 5.2 on 2025-06-16 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_remove_cryptodetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cryptodetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
