# Generated by Django 5.2 on 2025-06-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_cryptodetails_created_at_cryptodetails_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptodetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cryptodetails',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cryptodetails',
            name='updated_at',
        ),
    ]
