# Generated by Django 5.2 on 2025-06-17 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_remove_cryptodetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cryptodetails',
            name='currency',
            field=models.CharField(default='BTC', max_length=20),
        ),
        migrations.AddField(
            model_name='cryptodetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cryptodetails',
            name='exchange_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
