# Generated by Django 5.2 on 2025-06-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_commissioningprofile_level_1_percentage_and_more'),
        ('adminPanel', '0008_cryptodetails_created_at_cryptodetails_currency_and_more'),
    ]

    operations = [
    ]
