# Generated by Django 5.2 on 2025-06-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0009_merge_20250626_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptodetails',
            options={'verbose_name': 'Crypto Details', 'verbose_name_plural': 'Crypto Details'},
        ),
        migrations.AddField(
            model_name='cryptodetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
