# Generated by Django 5.2 on 2025-06-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_add_crypto_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptodetails',
            options={},
        ),
    ]
