# Generated by Django 5.2 on 2025-07-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0011_alter_cryptodetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code for IB users.', max_length=20, null=True, unique=True),
        ),
    ]
