# Generated by Django 5.2 on 2025-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0012_customuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code_used',
            field=models.CharField(blank=True, help_text='Referral code used at registration.', max_length=20, null=True),
        ),
    ]
