# Generated by Django 5.2 on 2025-07-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0014_tradegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradegroup',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default group for real accounts?'),
        ),
        migrations.AddField(
            model_name='tradegroup',
            name='is_demo_default',
            field=models.BooleanField(default=False, help_text='Is this the default group for demo accounts?'),
        ),
    ]
