# Generated by Django 5.2 on 2025-07-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0015_tradegroup_is_default_tradegroup_is_demo_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradegroup',
            name='alias',
            field=models.CharField(blank=True, help_text='Optional display name for the group', max_length=100, null=True),
        ),
    ]
