# Generated by Django 5.2 on 2025-07-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0016_auto_20250709_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetailsrequest',
            name='branch',
        ),
        migrations.AddField(
            model_name='bankdetailsrequest',
            name='bank_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank_docs/'),
        ),
        migrations.AddField(
            model_name='bankdetailsrequest',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
