# Generated by Django 5.2 on 2025-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0018_commissioningprofile_level_percentages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Verification status for the user.', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='is_pending',
            field=models.BooleanField(default=True, help_text='Indicates if the trading account is pending activation.'),
        ),
    ]
