# Generated by Django 4.2.7 on 2025-07-28 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0019_customuser_verification_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGenerationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Monthly Reports', help_text='Name of the schedule', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether automatic report generation is active')),
                ('generation_day', models.PositiveIntegerField(default=1, help_text='Day of the month to generate reports (1-28)')),
                ('include_all_users', models.BooleanField(default=True, help_text='Include all users in report generation')),
                ('email_from', models.EmailField(default='reports@yourcompany.com', help_text='Email address to send reports from', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time reports were generated', null=True)),
                ('specific_users', models.ManyToManyField(blank=True, help_text='Specific users to include (if not all users)', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Generation Schedule',
                'verbose_name_plural': 'Report Generation Schedules',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year of the report (e.g., 2024)')),
                ('month', models.PositiveIntegerField(help_text='Month of the report (1-12)')),
                ('report_file', models.FileField(blank=True, help_text='Generated PDF report file', null=True, upload_to='reports/monthly/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed')], default='pending', help_text='Status of the report generation and email', max_length=20)),
                ('password_hint', models.CharField(default='DOB in DDMMYYYY format', help_text='Hint for the PDF password', max_length=50)),
                ('email_attempts', models.PositiveIntegerField(default=0, help_text='Number of email sending attempts')),
                ('last_email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp of last email attempt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User for whom this report is generated', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Trade Report',
                'verbose_name_plural': 'Monthly Trade Reports',
                'ordering': ['-year', '-month', 'user__first_name'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
