# Generated by Django 4.2.7 on 2025-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0020_reportgenerationschedule_monthlytradereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytradereport',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total commission earned in the report period', max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlytradereport',
            name='total_trades',
            field=models.PositiveIntegerField(default=0, help_text='Total number of trades in the report period'),
        ),
        migrations.AddField(
            model_name='monthlytradereport',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total trading volume in the report period', max_digits=20),
        ),
    ]
