# Generated by Django 4.2.7 on 2025-07-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0021_monthlytradereport_total_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytradereport',
            name='password_hint',
            field=models.CharField(default='DOB in DDMMYYYY format', help_text='Hint for the PDF password', max_length=255),
        ),
    ]
