# Generated by Django 5.2 on 2025-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0022_alter_monthlytradereport_password_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code_used',
            field=models.CharField(blank=True, help_text='Referral code used at registration.', max_length=100, null=True),
        ),
    ]
