# Generated by Django 5.2 on 2025-07-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0023_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
