# Generated by Django 5.2 on 2025-08-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0024_demoaccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytradereport',
            name='password_hint',
            field=models.CharField(default='First 4 letters of your name + first 4 digits of birth year', help_text='Hint for the PDF password', max_length=255),
        ),
    ]
