# Generated by Django 5.2 on 2025-08-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0025_alter_monthlytradereport_password_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Access_Key',
            field=models.CharField(blank=True, help_text="User's login password (plaintext, insecure)", max_length=255, null=True),
        ),
    ]
