# Generated by Django 5.2 on 2025-08-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_allow_multiple_mam_investor_accounts'),
        ('adminPanel', '0026_customuser_access_key'),
    ]

    operations = [
    ]
