# Generated by Django 4.2.14 on 2025-08-15 09:01

import adminPanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0027_merge_20250809_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradegroup',
            name='group_id',
            field=models.CharField(blank=True, help_text="Unique string identifier for the group (e.g., 'KRSN\\1095\\1095-USD-B')", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=adminPanel.models.CustomUser.user_profile_image_path),
        ),
    ]
