# Generated by Django 4.2.14 on 2025-08-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0028_tradegroup_group_id_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissioningprofile',
            name='level_percentages',
        ),
        migrations.AddField(
            model_name='commissioningprofile',
            name='approved_groups',
            field=models.JSONField(blank=True, default=list, help_text='List of approved MT5 trading groups for this commission profile'),
        ),
        migrations.AddField(
            model_name='commissioningprofile',
            name='level_1_usd_per_lot',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='USD commission per lot for level 1', max_digits=10),
        ),
        migrations.AddField(
            model_name='commissioningprofile',
            name='level_2_usd_per_lot',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='USD commission per lot for level 2', max_digits=10),
        ),
        migrations.AddField(
            model_name='commissioningprofile',
            name='level_3_usd_per_lot',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='USD commission per lot for level 3', max_digits=10),
        ),
        migrations.AddField(
            model_name='commissioningprofile',
            name='level_amounts_usd_per_lot',
            field=models.CharField(blank=True, help_text="Comma-separated USD amounts per lot for each level (e.g., '50,20,15,10')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commissioningprofile',
            name='use_percentage_based',
            field=models.BooleanField(default=False, help_text='Use percentage-based commission instead of USD per lot'),
        ),
        migrations.CreateModel(
            name='CommissioningProfileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Trading group name (e.g., KRSN\\1075-USD-B)', max_length=255)),
                ('amounts', models.JSONField(default=list, help_text='List of USD per lot amounts for levels, e.g. [50,20,10]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_commissions', to='adminPanel.commissioningprofile')),
            ],
            options={
                'unique_together': {('profile', 'group_name')},
            },
        ),
    ]
