# Generated by Django 4.2.14 on 2025-08-26 11:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0029_remove_commissioningprofile_level_percentages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='copy_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.00'), help_text='The coefficient factor used for trade copying in MAM investment accounts.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='copy_mode',
            field=models.CharField(blank=True, choices=[('balance_ratio', 'By Balance Ratio'), ('fixed_multiple', 'By Fixed Multiple')], default='balance_ratio', help_text='The copy mode for MAM investment accounts (Balance Ratio or Fixed Multiple).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_category',
            field=models.CharField(choices=[('client', 'Client'), ('management', 'Management')], default='client', max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='create', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Transaction status.', max_length=50),
        ),
    ]
