# Generated by Django 4.2.14 on 2025-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0031_tradingaccount_copy_multiplier_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='copy_multiplier_mode',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='copy_trade_enabled',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='fixed_copy_multiplier',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='max_copy_multiplier',
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Admin approval/rejection comment for this transaction.', null=True),
        ),
    ]
