# Generated by Django 4.2.14 on 2025-08-28 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0032_remove_tradingaccount_copy_multiplier_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='copy_multiplier_mode',
            field=models.CharField(default='balance_ratio', help_text='Compatibility field for older DB schemas (stores copy mode as text).', max_length=50),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='copy_trade_enabled',
            field=models.BooleanField(default=False, help_text='Whether copy trading is enabled for this account.'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='fixed_copy_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Compatibility numeric multiplier used when copy mode is fixed multiple.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='max_copy_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Compatibility max multiplier for copy settings.', max_digits=10),
        ),
    ]
