# Generated by Django 4.2.14 on 2025-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0033_tradingaccount_copy_multiplier_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontransaction',
            name='lot_size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
