# Generated by Django 5.2 on 2025-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0035_alter_commissiontransaction_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5SendDedup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='adminPanel__created_feb4f9_idx')],
            },
        ),
    ]
