# Generated by Django 5.2 on 2025-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0036_mt5senddedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontransaction',
            name='source',
            field=models.CharField(default='mt5', max_length=100),
        ),
    ]
