# Generated by Django 5.2 on 2025-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0037_commissiontransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioningprofile',
            name='dynamic_levels',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic level configuration with percentage and/or USD per lot for each level'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='deal_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='mt5_close_time',
            field=models.DateTimeField(blank=True, help_text='Actual MT5 position close time', null=True),
        ),
        migrations.AlterField(
            model_name='commissiontransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='commissiontransaction',
            name='position_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['position_id', 'client_trading_account', 'ib_user'], name='position_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['ib_user', 'created_at'], name='ib_commissions_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['client_user', 'created_at'], name='client_commissions_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['client_trading_account', 'created_at'], name='account_commissions_idx'),
        ),
    ]
