# Generated by Django 5.2 on 2025-10-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0038_commissioningprofile_dynamic_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='dual_trade_enabled',
            field=models.BooleanField(default=False, help_text='Whether to enable multiple trade copying (legacy field, use multi_trade_count instead).'),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='multi_trade_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of times to copy each master trade to the investor account (1-10).'),
        ),
    ]
