# Generated by Django 5.2 on 2025-10-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0039_tradingaccount_dual_trade_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Access_Key',
        ),
    ]
