# Generated by Django 5.2 on 2025-10-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0040_remove_customuser_access_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
