# Generated by Django 5.2 on 2025-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0043_delete_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgenerationschedule',
            name='email_from',
            field=models.EmailField(default='support@vtindex.com', help_text='Email address to send reports from', max_length=254),
        ),
    ]
