# Generated by Django 5.2 on 2025-11-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0044_alter_reportgenerationschedule_email_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='activitylog_user_timestamp_idx'),
        ),
    ]
