# Generated by Django 5.2 on 2025-11-11 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0045_customuser_last_login_at_customuser_last_login_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('IB', 'IB Request'), ('BANK', 'Bank Transaction'), ('CRYPTO', 'Crypto Transaction'), ('PROFILE', 'Profile Change'), ('DOCUMENT', 'Document Upload'), ('ACCOUNT', 'Account Creation')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('created', 'Created'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='adminPanel__created_637cd6_idx'), models.Index(fields=['user', '-created_at'], name='adminPanel__user_id_3b7759_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='adminPanel__user_id_67843e_idx')],
            },
        ),
    ]
