# Generated by Django 5.2 on 2025-12-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0046_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='migrated_to_old_withdrawal',
            field=models.BooleanField(default=False, help_text='Whether this transaction has been migrated to the old withdrawal system.'),
        ),
    ]
