# Generated by Django 5.2 on 2026-01-03 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0047_transaction_migrated_to_old_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='migrated_to_old_withdrawal',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False, help_text='Whether the user has been approved by admin to access the platform.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='old_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Compatibility field for legacy commission values.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='old_commission_withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Compatibility field for legacy commission withdrawal values.', max_digits=12, null=True),
        ),
    ]
