# Generated by Django 5.2 on 2026-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0048_remove_transaction_migrated_to_old_withdrawal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='migrated_to_old_withdrawal',
            field=models.BooleanField(default=False, help_text='Whether this transaction has been migrated to the old withdrawal system.'),
        ),
    ]
