# Generated by Django 5.2 on 2026-01-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0049_transaction_migrated_to_old_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='status_code',
            field=models.IntegerField(blank=True, help_text='HTTP status code of the response', null=True),
        ),
    ]
