# Generated by Django 5.2 on 2025-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(max_length=100, verbose_name='Server IP Address with Port')),
                ('real_account_login', models.CharField(max_length=100, verbose_name='Real Account Login ID')),
                ('real_account_password', models.CharField(max_length=100, verbose_name='Real Account Password')),
                ('server_name_client', models.CharField(max_length=100, verbose_name='Server Name for Live Accounts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server Setting',
                'verbose_name_plural': 'Server Settings',
            },
        ),
    ]
