# Generated by Django 5.2 on 2025-06-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5GroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('leverage', models.IntegerField(default=100)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'mt5_group_config',
                'ordering': ['group_name'],
            },
        ),
    ]
